QUOTES = [
    "Deploy your dreams, not just your code.",
    "Infrastructure is poetry written in YAML.",
    "Version control your life, commit often.",
    "In DevOps, the only constant is automation.",
    "Resilience is built with retries and backoffs.",
    "Push to prod like you mean it—after testing, of course.",
    "Every outage has a story; write yours with logs.",
    "CI/CD isn’t just a pipeline, it’s a lifestyle.",
    "Dev without Ops is like code without runtime.",
    "Containers don’t solve everything, but they sure help.",
    "Monitor everything, trust nothing.",
    "Plan. Apply. Destroy. Repeat.",
    "Downtime teaches more than uptime ever could.",
    "Think in versions, build in modules.",
    "Secrets don’t belong in your repo—or your screenshots.",
    "The shell giveth, and the shell taketh away.",
    "DevOps is 10% code and 90% communication.",
    "Alert fatigue is real. Respect the pager.",
    "Logs are your future self’s diary—be kind.",
    "Build once, deploy everywhere.",
    "Immutable infrastructure means fewer surprises.",
    "Terraform like an artist, deploy like a machine.",
    "YAML is love. YAML is pain.",
    "Your pipeline is only as good as your last commit.",
    "Debugging in prod is a team sport.",
    "Uptime isn’t luck. It’s automation.",
    "A good dashboard tells the truth faster.",
    "If you can’t automate it, script it. If you can’t script it, document it.",
    "Scaling fixes load, not code.",
    "Ship small, fail small, recover fast.",
    "An outage is just a high-stakes retrospective.",
    "Your backups are only real if you've restored them.",
    "Treat servers like cattle, not pets.",
    "DevOps is empathy, codified.",
    "Rerunning jobs isn’t a strategy.",
    "Security is everyone’s job, not just a role.",
    "Make it idempotent or make it hurt.",
    "Manual steps are just automation waiting to happen.",
    "Monitoring is knowing, alerting is caring.",
    "Good pipelines are boring. Be proud of boring.",
    "Change is scary—automation makes it less so.",
    "Downtime is inevitable, chaos is optional.",
    "Ops without Dev is like a car without a driver.",
    "If it's not in source control, it doesn’t exist.",
    "Test early, test often, test in prod (carefully).",
    "Latency hides in the shadows—shine a light.",
    "The only good snowflake is in a dashboard.",
    "Document it now, or explain it during an incident.",
    "From build to prod, every step should be a click or a script.",
    "An SLA without observability is a wish.",
]

