# To build and push the image to Docker Hub

name: Build, Push and Deploy to ECS

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: containers/
        file: containers/Dockerfile
        push: true
        tags: frankfolabi/flask-quotes:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: Force new ECS deployment
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        cluster: flask-quotes-cluster           
        service: flask-quotes-task          
        task-definition: flask-quotes-cluster
        force-new-deployment: true
